namespace: t_systems_mms
name: icinga_director
version: 1.13.0
readme: README.md
authors:
  - Sebastian Gumprich <sebastian.gumprich@t-systems.com>
  - Lars Krahl <lars.krahl@t-systems.com>
description: >-
  This collection contains Ansible modules to change objects in Icinga 2 using
  the director API.
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - icinga
  - monitoring
dependencies: {}
repository: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-director'
documentation: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-director'
homepage: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-director'
issues: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-director/issues'
build_ignore:
  - vsc-snippets
  - codecov.yml
  - .github
  - hacking
  - requirements.txt
  - test-requirements.txt
  - tests
  - .tox
  - tox.ini
  - .yamllint
