---
- name: Icinga_user_group
  icinga_user_group:
    url: "{{ icinga_url }}"
    use_proxy: "{{ icinga_use_proxy | default(omit) }}"
    validate_certs: "{{ icinga_validate_certs | default(omit) }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
    client_cert: "{{ icinga_client_cert | default(omit) }}"
    client_key: "{{ icinga_client_key | default(omit) }}"
    state: "{{ user_group.state | default(omit) }}"
    object_name: "{{ user_group.name }}"
    display_name: "{{ user_group.display_name | default(omit) }}"
    disabled: "{{ user_group.disabled | default(omit) }}"
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  loop: "{{ icinga_user_groups }}"
  loop_control:
    loop_var: user_group
  tags: user_group
  notify: config_deploy
