---
# servicegroup.1 = servicegroup array
# servicegroup.0 = icinga_servicegroup attribute
- name: icinga_servicegroup
  icinga_servicegroup:
    url: "{{ icinga_url }}"
    use_proxy: "{{ icinga_use_proxy | default(omit) }}"
    validate_certs: "{{ icinga_validate_certs | default(omit) }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
    client_cert: "{{ icinga_client_cert | default(omit) }}"
    client_key: "{{ icinga_client_key | default(omit) }}"
    state: "{{ servicegroup.0.state | default(omit) }}"
    object_name: "{{ servicegroup.1 }}"
    display_name: "{{ servicegroup.0.display_name | default(omit) }}"
    assign_filter: "{{ servicegroup.0.assign_filter | default(omit) }}"
  loop: "{{ icinga_servicegroups|subelements('servicegroup_object') }}"
  loop_control:
    loop_var: servicegroup
  tags: servicegroup
