---
- name: Icinga_host_info
  telekom_mms.icinga_director.icinga_host_info:
    url: "{{ icinga_url }}"
    use_proxy: "{{ icinga_use_proxy | default(omit) }}"
    validate_certs: "{{ icinga_validate_certs | default(omit) }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
    client_cert: "{{ icinga_client_cert | default(omit) }}"
    client_key: "{{ icinga_client_key | default(omit) }}"
    query: "{{ host_info.query | default(omit) }}"
    resolved: "{{ host_info.resolved | default(omit) }}"
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  loop: "{{ icinga_hosts_info }}"
  loop_control:
    loop_var: host_info
  tags: host_info
