---
- name: Icinga_servicegroup
  icinga_servicegroup:
    url: "{{ icinga_url }}"
    use_proxy: "{{ icinga_use_proxy | default(omit) }}"
    validate_certs: "{{ icinga_validate_certs | default(omit) }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
    client_cert: "{{ icinga_client_cert | default(omit) }}"
    client_key: "{{ icinga_client_key | default(omit) }}"
    state: "{{ servicegroup.state | default(omit) }}"
    object_name: "{{ servicegroup.name }}"
    display_name: "{{ servicegroup.display_name | default(omit) }}"
    assign_filter: "{{ servicegroup.assign_filter | default(omit) }}"
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  loop: "{{ icinga_servicegroups }}"
  loop_control:
    loop_var: servicegroup
  tags: servicegroup
  notify: config_deploy
