---
- name: Icinga_importsource
  telekom_mms.icinga_director.icinga_importsource:
    url: "{{ icinga_url }}"
    use_proxy: "{{ icinga_use_proxy | default(omit) }}"
    validate_certs: "{{ icinga_validate_certs | default(omit) }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
    client_cert: "{{ icinga_client_cert | default(omit) }}"
    client_key: "{{ icinga_client_key | default(omit) }}"
    state: "{{ importsource.state | default(omit) }}"
    source_name: "{{ importsource.name }}"
    key_column: "{{ importsource.key_column | default(omit) }}"
    provider_class: "{{ importsource.provider_class | default(omit) }}"
    description: "{{ importsource.description | default(omit) }}"
    settings: "{{ importsource.settings | default(omit) }}"
    modifiers: "{{ importsource.modifiers | default(omit) }}"
    append: "{{ importsource.append | default(omit) }}"
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  loop: "{{ icinga_importsources }}"
  loop_control:
    loop_var: importsource
  tags: importsource
  notify: config_deploy
