---
collections:
  - telekom_mms.icinga_director
galaxy_info:
  role_name: ansible_icinga
  author: telekom_mms
  description: This role is used to configure an Icinga Instance over its Icinga Director.
  license: GPLv3
  min_ansible_version: 2.9
  galaxy_tags:
    - icinga
  platforms:
    - name: all
