---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@d170c759e28cb7fda81f45e25d628984e7d90696" # main
