---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@87a8b04370d5d8dd0a6d8af0e65184dbebad6bcf" # main
