---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@main"
