---
name: Publish collection to Ansible Galaxy

on:
  release:
    types:
      - released

jobs:
  deploy:
    uses: telekom-mms/.github/.github/workflows/ansible-galaxy-publish.yml@d5e3d5d90a0f9d6b0527143d5497fe88d058d4bc # main
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
      GH_BRANCH_PROTECTION_APP_TOKEN: ${{ secrets.GH_BRANCH_PROTECTION_APP_TOKEN }}
