---
name: Publish collection to Ansible Galaxy

on:
  release:
    types:
      - released

jobs:
  deploy:
    uses: telekom-mms/.github/.github/workflows/ansible-galaxy-publish.yml@0915e4a25cc07af95b7039c3539df1791ac9d909 # main
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
      GH_BRANCH_PROTECTION_APP_TOKEN: ${{ secrets.GH_BRANCH_PROTECTION_APP_TOKEN }}
